### ISSUE TITLE
Highcharts

### ISSUE THREAD

**Issue by eportico** [allegro/tipboard#12]
Hi guy,
I am creating a tile to include in Tipboard highchart. I do not really know how to include the script in Tipboard hightchars.js. I would appreciate your help

**Comment by syphernl** [comment]
@xliiv Unfortunately you cannot add this to your `settings-local.py` since this particular key is being overwritten by the actual `settings.py`.

**Comment by xliiv** [comment]
Second that, so the ticket #13 was created.

**Comment by syphernl** [comment]
Ah, I see :)
