### ISSUE TITLE
Homedir settings does not accept all possible settings

### ISSUE THREAD

**Issue by xliiv** [allegro/tipboard#13]
It's impossible to change for example _TIPBOARD_JAVASCRIPTS_ in _~/.tipboard/settings-local.py_.
Now you need to change it in tipboard source settings (https://github.com/allegro/tipboard/blob/develop/tipboard/settings.py).
Check also other settings.. .

**Comment by syphernl** [comment]
Alternatively support for RequireJS could be added. 

This is pretty easy to achieve:
* Add `require.js` to the `settings.py`
* From your module's js you can require any files using `requirejs(['/static/my-custom.js']);`

I have just tested this and seems to work just fine. 
Eventually the massive list of jQuery includes could be decreased as well so they are only included when needed (via requireJS)

**Comment by xliiv** [comment]
Great! You seem like you want to create a pull request? That's the spirit! :)
