### ISSUE TITLE
Custom Redis server location

### ISSUE THREAD

**Issue by csu** [allegro/tipboard#15]
Is there a way to specify a custom location for the Redis server? I'm trying to use an external Redis server, so it's not located at `localhost: 6379`.

**Comment by xor-xor** [comment]
Sure. Just overwrite [these defaults](https://github.com/allegro/tipboard/blob/develop/tipboard/settings.py#L14) in your local settings (i.e., `~/.tipboard/settings-local.py`).

**Comment by csu** [comment]
Awesome! Thanks!

**Comment by csu** [comment]
I have a Redis URI in the format: `redis://redacted-username:redacted-password@redacted-server-thing.com:port`. Should I put the username, password, and hostname all in REDIS_HOST and then the port in REDIS_PORT?

**Comment by xor-xor** [comment]
Yes, I would do that. Let us know if that worked.

**Comment by csu** [comment]
I got:
```
File "/app/.tipboard/settings-local.py", line 12 
      REDIS_HOST = asdfasd:asdfasdfadf@asdfasdfasdf.com 
                                   ^ 
  SyntaxError: invalid syntax 
```

(The arrow is pointing at the colon)

**Comment by xliiv** [comment]
Probabbly missing quotes.. .
Try this:
    REDIS_HOST = 'redacted-username:redacted-password@redacted-server-thing.com'
    REDIS_PORT = 6379

**Comment by csu** [comment]
Ah, that was it. I'm adding it through my Procfile with `printf 'asdhfksajhfadf' >> ~/.tipboard/settings-local.py`, so I didn't catch that at first :stuck_out_tongue:. Trying it again.

**Comment by csu** [comment]
```
Traceback (most recent call last): 
  File "/app/.heroku/python/bin/tipboard", line 9, in <module> 
    load_entry_point('tipboard==1.4.0', 'console_scripts', 'tipboard')() 
  File "/app/.heroku/python/lib/python2.7/site-packages/tipboard/console.py", line 233, in main 
    address=arguments.get('<host>'), port=arguments.get('<port>') 
  File "/app/.heroku/python/lib/python2.7/site-packages/tipboard/console.py", line 158, in runserver 
    populate_key_cache() 
  File "/app/.heroku/python/lib/python2.7/site-packages/tipboard/console.py", line 137, in populate_key_cache 
    for key in client.keys(keys): 
  File "/app/.heroku/python/lib/python2.7/site-packages/redis/client.py", line 637, in keys 
    return self.execute_command('KEYS', pattern) 
  File "/app/.heroku/python/lib/python2.7/site-packages/redis/client.py", line 381, in execute_command 
    connection.send_command(*args) 
  File "/app/.heroku/python/lib/python2.7/site-packages/redis/connection.py", line 299, in send_command 
    self.send_packed_command(self.pack_command(*args)) 
  File "/app/.heroku/python/lib/python2.7/site-packages/redis/connection.py", line 281, in send_packed_command 
    self.connect() 
  File "/app/.heroku/python/lib/python2.7/site-packages/redis/connection.py", line 229, in connect 
Raven is not configured (logging is disabled). Please see the documentation for more information. 
    raise ConnectionError(self._error_message(e)) 
redis.exceptions.ConnectionError: Error -2 connecting <user>:<pass>@<hostname>:<port>. Name or service not known. 
```

**Comment by csu** [comment]
Also, for `REDIS_DB`, I have a db name but not a number. Does it accept a string as well? I'm not overwriting it right now.

**Comment by xor-xor** [comment]
String instead of number? Are you sure? Which version of Redis do you use?

**Comment by csu** [comment]
I've tried using both Redis Cloud and Redis To Go. Redis Cloud uses a string, Redis To Go has `databases 1` in the config. Is it 0-indexed?
![screen shot 2015-02-05 at 12 32 53 pm](https://cloud.githubusercontent.com/assets/164822/6068712/3879f730-ad33-11e4-8b65-b2d77bacd40e.jpg)

**Comment by xliiv** [comment]
We haven't tested Tipboard in environment like yours.
I can't tell if we do it.

However it should work, because Tipboard connects (https://github.com/allegro/tipboard/blob/5bc92312da287984285bed418fc88dbeb4590fb7/tipboard/console.py#L135) redis the same way as this recommendation:
https://redislabs.com/python-redis

Redis version from requirements is: redis 2.7.5.

**Comment by csu** [comment]
Interesting. Apparently StrictRedis also has a password parameter:
```python
    def __init__(self, host='localhost', port=6379,
                 db=0, password=None, socket_timeout=None,
                 ...
```

There's also a `from_url` function that looks like it'd work:
```python
def from_url(cls, url, db=None, **kwargs):
        """
        Return a Redis client object configured from the given URL.
        For example::
            redis://[:password]@localhost:6379/0
            unix://[:password]@/path/to/socket.sock?db=0
```
