### ISSUE TITLE
Trigger refresh when tile configuration changes

### ISSUE THREAD

**Issue by syphernl** [allegro/tipboard#17]
It would be nice if the dashboard could be auto-refreshed whenever the configuration has changed. 
E.g. when a tile is added or removed.

**Comment by xliiv** [comment]
As a walkaround I'd do this:
Add:

    DEBUG = True

to:

    ~/.tipboard/settings-local.py

then refresh browser or set cyclic refreshing (some of browsers have such feature).

**Comment by syphernl** [comment]
Hmm, that doesn't appear to be working (at least not in Chromium)

**Comment by vi4m** [comment]
Please take a look at `livereload` python package, used for example by mkdocs. It works great across many operating systems.
