### ISSUE TITLE
[Suggestion] Add a comments searchbox

### ISSUE THREAD

**Issue by DonAndress** [allegro/tipboard#34]
HI.
I have a suggestion.
When sellers sell hundreds of items a month it's hard to find comments for just one specific item (auction number).
My suggestion - on a seller comments page add a searchbox to input a desired auction number to limit comments just to this one item.
Regards.

**Comment by xor-xor** [comment]
I'm not really sure if your suggestion is related to Tipboard in any possible way, but maybe I'm wrong..?

**Comment by xliiv** [comment]
This is `tipboard`:
http://allegro.tech/tipboard/
and you probably want to contact:
http://allegro.pl/
These are seperate projects.

**Comment by DonAndress** [comment]
Ops, I thought this was an official allegro.pl channel to communicate with their developers.
After all allegro.pl somehow gave me direction to this page.

Sorry guys.
