### ISSUE TITLE
Confusing docs / getting started guide

### ISSUE THREAD

**Issue by the4ndy** [allegro/tipboard#35]
I have read through the entire docs at http://tipboard.readthedocs.org/en/latest/ several times and it is making me feel very dumb. I have got my layout set (i used the default) I set the first tile template to "text" and gave it a title. I go through the documentation and eventually i come across the page with info on the "text" template, but no where can I find WHERE to input or HOW to input any of that data. I see NO lines in either config file (the yaml layout or the general settings), there is no instruction on WHERE something like the curl example would go. I am new to dashboards and even API's in general but I was hoping that there would be some ACTUAL EXAMPLES where they show you the file that needs to be edited and an example of HOW they edited it or where to put any data.  
  
At this point I have the dashboard installed, and I can edit the layout and edit the tile_template, tile_id, title, and classes (though there is no indication as to what this does) fields but there is no understandable documentation that tells me where to input the DATA for that tile.  
  
Please someone help :(

EDIT: I am not very smart at all....in the end I realized that I needed to push from somewhere to the tipboard. I tried running the curl command in the "text" template example and had no idea what "mykey" was (i used my api key, but that means its in the curl command twice, once in the url and once as a parameter). it turned out that key = the tile id (not too intuitive naming if you ask me). the tile= i guess is for type? I left this as "text" and its working ish now...  
  
I will just keep at it and hopefully figure it out, but I came to tipboard because of its advertised ease of use, and unfortuantely disappointed to find out that its not for beginners at all. I am someone who has had great success setting up and managing my home servers and now I want to create a dashboard for them, but I have little to no API knowledge and while i Know its not oyur responsibility to assist, i think bridging the gap between what the user ALREADY NEEDS and how to give that to tipboard properly could be documented a bit better.....idk

**Comment by xliiv** [comment]
Maybe full example including:
- layout
- script sending data
would help, what do you think?
