### ISSUE TITLE
404 error for static files

### ISSUE THREAD

**Issue by Cosbgn** [allegro/tipboard#36]
Hi, I'm getting several 404 errors for static files when I launch my dashboard: 

> (venv) CMac:Tipboard_app cosbgn$ tipboard runserver
Raven is not configured (logging is disabled). Please see the documentation for more information.
[I 160506 16:24:13 console:145] Following keys already in Redis: 
[I 160506 16:24:13 console:160] Listening on port localhost:7272...
[I 160506 16:24:43 web:1946] 304 GET / (::1) 97.68ms
[W 160506 16:24:44 web:1946] 404 GET /static/css/reset.css (::1) 57.44ms
[W 160506 16:24:44 web:1946] 404 GET /static/css/jquery.jqplot.css (::1) 0.88ms
[W 160506 16:24:44 web:1946] 404 GET /static/css/layout.css (::1) 1.21ms
[W 160506 16:24:44 web:1946] 404 GET /static/js/lib/jquery.js (::1) 1.12ms
[W 160506 16:24:44 web:1946] 404 GET /static/js/flipboard.js (::1) 1.17ms
[W 160506 16:24:45 web:1946] 404 GET /static/js/lib/require.js (::1) 1.12ms
[I 160506 16:24:47 web:1946] 304 GET / (::1) 155.84ms
[W 160506 16:24:47 web:1946] 404 GET /static/css/reset.css (::1) 2.75ms
[W 160506 16:24:47 web:1946] 404 GET /static/css/layout.css (::1) 1.15ms
[W 160506 16:24:47 web:1946] 404 GET /static/css/jquery.jqplot.css (::1) 1.11ms
[W 160506 16:24:47 web:1946] 404 GET /static/js/lib/require.js (::1) 10.83ms
[W 160506 16:24:47 web:1946] 404 GET /static/js/flipboard.js (::1) 1.45ms
[W 160506 16:24:47 web:1946] 404 GET /static/js/lib/jquery.js (::1) 1.42ms

Then when I go on localhost:7272 I see only [this white box](https://snag.gy/8HgyS1.jpg) and not the dashboard, do you know why this happens?

Thanks!

![image](https://cloud.githubusercontent.com/assets/17546283/15076025/de947100-13a7-11e6-80fd-8a85cffe2117.png)

**Comment by xliiv** [comment]
Did you instal tipboard by pip? Can you describe more what you did?
I've just done this in newly created virtualenv:
```
pip install tipboard
tipboard runserver
```
and everything works.

**Comment by Cosbgn** [comment]
When I try to install tipboard via pip I get the following error: 

```
Collecting tipboard
  Using cached tipboard-1.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    error in tipboard setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "','"
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/4r/569bh7c1295c2zr4hhv12b_40000gn/T/pip-build-PhEJqb/tipboard/
```
As a work around I've used instead the command `pip install git+https://github.com/allegro/tipboard`
The installation works but I get the 404 errors. 

Any ideas how to either problem?
Thanks!

**Comment by mkurek** [comment]
@Cosbgn what python version are you using? are you installing it in virtualenv? Could you paste here your content of `~/.tipboard/settings-local.py` and output of `pip freeze`?

**Comment by Cosbgn** [comment]
Hi, I'm using Python 2.7.10 and virtualenv.

The content of settings-local.py is: 
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

PROJECT_NAME = 'kpi_dashboard'
API_KEY = 'a8e0e4e8f58f4c0aa4f3e9ef2afc73b2'
```
The output of `pip freeze` is:
```
(venv) CMac:Tipboard_app cosbgn$ pip freeze
appnope==0.1.0
attrs==15.2.0
backports-abc==0.4
backports.ssl-match-hostname==3.4.0.2
beautifulsoup4==4.4.1
cffi==1.5.2
conda==4.0.5
conda-env==2.4.5
cryptography==1.3
cssselect==0.9.1
DateTime==4.1
decorator==4.0.6
django-extensions==1.6.1
docopt==0.6.1
docutils==0.12
enum34==1.1.2
Flask==0.10.1
google-api-python-client==1.5.0
httplib2==0.9.2
idna==2.0
ipaddress==1.0.14
ipykernel==4.2.2
ipython==4.1.1
ipython-genutils==0.1.0
ipywidgets==4.1.1
itsdangerous==0.24
Jinja2==2.7.3
jsonschema==2.4.0
jupyter==1.0.0
jupyter-client==4.1.1
jupyter-console==4.1.0
jupyter-core==4.0.6
jupyter-themer==0.1.2
lxml==3.6.0
MarkupSafe==0.23
mistune==0.7.1
mock==1.0.1
nbconvert==4.1.0
nbformat==4.0.1
nose==1.3.7
notebook==4.1.0
numpy==1.10.4
oauth2client==2.0.0.post1
oauthlib==1.0.3
pandas==0.18.0
path.py==0.0.0
pexpect==3.3
pickleshare==0.5
ptyprocess==0.5
pyasn1==0.1.9
pyasn1-modules==0.0.8
pycosat==0.6.1
pycparser==2.14
pycrypto==2.6.1
Pygments==2.1
pymongo==2.8
pyOpenSSL==0.15.1
python-dateutil==2.5.0
python-twitter==2.2
pytz==2015.7
PyYAML==3.10
pyzmq==15.2.0
qtconsole==4.1.1
queuelib==1.4.2
raven==3.5.2
redis==2.7.5
request==0.0.2
requests==1.2.3
requests-oauthlib==0.6.1
rsa==3.3
Scrapy==1.0.5
service-identity==16.0.0
simplegeneric==0.8.1
simplejson==3.8.2
singledispatch==3.4.0.3
six==1.4.1
Sphinx==1.2.2
sphinxcontrib-httpdomain==1.3.0
terminado==0.5
tipboard==1.4.0
tornado==3.0.1
tornado-redis==2.4.2
traitlets==4.1.0
Twisted==16.0.0
uritemplate==0.6
virtualenv==15.0.1
w3lib==1.12.0
Werkzeug==0.10
zope.interface==4.1.3
```
Thanks

**Comment by xliiv** [comment]
What OS are you using?
The problem with static could be file permission, but you did install from source.
This is weird, i did all ("pip install tipboard" and "pip install pip install git+https://github.com/allegro/tipboard) your cases and everything is ok.
I'm used:
- python 2.7.6
- pip 8.1.1.
- Ubuntu 14.04

**Comment by Cosbgn** [comment]
I'm using a Mac with OS X 10.11

**Comment by xliiv** [comment]
You've got a lot of packages in virtualenv. Create minimal setup by this script:

```
#!/bin/sh
cd ~
virtualenv tipboard-venv
source tipboard-venv/bin/activate
pip install -U pip
pip install git+https://github.com/allegro/tipboard@develop#egg=tipboard
tipboard runserver
```

`pip freeze` (from virtualenv tipboard-venv) gives me only

```
docopt==0.6.1
docutils==0.12
Jinja2==2.8
MarkupSafe==0.23
mock==1.0.1
Pygments==2.1.3
PyYAML==3.10
raven==3.5.2
redis==2.7.5
requests==1.2.3
six==1.4.1
Sphinx==1.2.2
sphinxcontrib-httpdomain==1.3.0
tipboard==1.4.0
tornado==3.0.1
tornado-redis==2.4.2
```

**Comment by Cosbgn** [comment]
I've created a new environment and now everything works! 
Thank you very much!

**Comment by PGFL** [comment]
@Cosbgn @xliiv I was just trying the same thing and keep getting a different kind of error when i try to run tipboard, can you help what am i missing?

 tipboard runserver
Raven is not configured (logging is disabled). Please see the documentation for more information.
Traceback (most recent call last):
  File "/Users/u779400/tipboard-venv/bin/tipboard", line 10, in <module>
    sys.exit(main())
  File "/Users/u779400/tipboard-venv/lib/python2.7/site-packages/tipboard/console.py", line 233, in main
    address=arguments.get('<host>'), port=arguments.get('<port>')
  File "/Users/u779400/tipboard-venv/lib/python2.7/site-packages/tipboard/console.py", line 158, in runserver
    populate_key_cache()
  File "/Users/u779400/tipboard-venv/lib/python2.7/site-packages/tipboard/console.py", line 137, in populate_key_cache
    for key in client.keys(keys):
  File "/Users/u779400/tipboard-venv/lib/python2.7/site-packages/redis/client.py", line 637, in keys
    return self.execute_command('KEYS', pattern)
  File "/Users/u779400/tipboard-venv/lib/python2.7/site-packages/redis/client.py", line 381, in execute_command
    connection.send_command(*args)
  File "/Users/u779400/tipboard-venv/lib/python2.7/site-packages/redis/connection.py", line 299, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/Users/u779400/tipboard-venv/lib/python2.7/site-packages/redis/connection.py", line 281, in send_packed_command
    self.connect()
  File "/Users/u779400/tipboard-venv/lib/python2.7/site-packages/redis/connection.py", line 229, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting localhost:6379. Connection refused.
