### ISSUE TITLE
Cannot install tipboard using pip (invalid install_requires)

### ISSUE THREAD

**Issue by samupl** [allegro/tipboard#40]
When trying to install tipboard through pip, the following error occurs:

```
$ pip --no-cache-dir install tipboard
Collecting tipboard
  Downloading tipboard-1.4.0.tar.gz (1.5MB)
    100% |████████████████████████████████| 1.5MB 6.7MB/s 
    Complete output from command python setup.py egg_info:
    error in tipboard setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "','"
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/js/pip-build-8u8mD0/tipboard/
```

Python and PIP version:
```
Python 2.7.12
pip 9.0.1 from /home/js/.virtualenvs/tb-venv/lib/python2.7/site-packages (python 2.7)
```

The same happens on system-level pip/python as well as on virtualenv level.

**Comment by samupl** [comment]
I can see that the current `requirements.txt` file is valid. However, the package downloaded from pip seems to have a comma on the last line:

```
[...]
Sphinx==1.2.2,
sphinxcontrib-httpdomain==1.3.0,
```

Probably re-uploading the package to pypi or releasing it with a newer package version will be enough.

**Comment by ghost** [comment]
New version has been uploaded:
https://pypi.python.org/pypi/tipboard

**Comment by samupl** [comment]
Confirmed, new version installs correctly. Thank you.
