### ISSUE TITLE
Dependency issue when installing tipboard through pip

### ISSUE THREAD

**Issue by fostecli000** [allegro/tipboard#46]
I was following the instructions closely, and upon reaching this step got slightly stuck:

`(tb-env)$ pip install tipboard`

On a Ubuntu 16.04.2 LTS computer, I had to use this version of that command to fix the dependency issue.

`(tb-env)$ pip install tipboard --ignore-installed six`

**Comment by vi4m** [comment]
Thanks for reporting it. @xliiv can you reproduce it?

**Comment by mkurek** [comment]
@ziollek fix it in #44, but we didn't release new version with this fix. I've released version 1.4.2 to pypi and it's fixed now (tested on docker with ubuntu 16.04).
