### ISSUE TITLE
pypi package out of date - new release possible

### ISSUE THREAD

**Issue by TechnoTaff** [allegro/tipboard#57]
Hi Guys,

We've implemented tipboard behind an SSL reverse proxy, this causes websockets to fail because secure websockets is required.

The [fix](https://github.com/allegro/tipboard/commit/5b21f48810f608bcb0649dbb70a0a9d82778d9b5) is actually in the develop branch on this repo but a new version (1.4.3?) would be required to deploy from PyPI.

Is there a chance someone could tag 1.4.3 and push the update into PyPI?

]-[

**Comment by mkurek** [comment]
Hi @TechnoTaff - I've uploaded `tipboard==1.4.3` to pypi.

**Comment by TechnoTaff** [comment]
Thank you!!!
