### ISSUE TITLE
NameError: name 'execfile' is not defined

### ISSUE THREAD

**Issue by gregology** [allegro/tipboard#66]
Hey Team, I'm trying to setup tipboard on a fresh Ubuntu 18.04LTS VPS. I followed the quick start guide and installed via pip. However I'm getting this error when I try and create a new dashboard. Does tipboard work with Python3? Or is this caused by some other issue?

```
Traceback (most recent call last):
  File "/home/greg/virtualenvs/tipboard/bin/tipboard", line 6, in <module>
    from tipboard.console import main
  File "/home/greg/virtualenvs/tipboard/lib/python3.6/site-packages/tipboard/console.py", line 48, in <module>
    from tipboard import __version__, settings
  File "/home/greg/virtualenvs/tipboard/lib/python3.6/site-packages/tipboard/settings.py", line 56, in <module>
    execfile(
NameError: name 'execfile' is not defined
```

**Comment by gregology** [comment]
After further digging into the [docs](https://tipboard.readthedocs.io/en/latest/installation.html#installation), I see that tipboard requires python 2.7. Are there plans to port this to 3+?

**Comment by vi4m** [comment]
I'm afraid we don't actively develop this project anymore. If anybody wants to work on porting this to Python 3 - we'll happily accept patches.

**Comment by the-maux** [comment]
@gregology @vi4m don't hesitate to check the PR #70  :)
